# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import memory_check_pb2 as src_dot_memory__check__pb2


class MemoryCheckStub(object):
    """Interface exported by the server.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.MemoryChat = channel.unary_unary(
                '/memorycheck.MemoryCheck/MemoryChat',
                request_serializer=src_dot_memory__check__pb2.Payload.SerializeToString,
                response_deserializer=src_dot_memory__check__pb2.Payload.FromString,
                )


class MemoryCheckServicer(object):
    """Interface exported by the server.
    """

    def MemoryChat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MemoryCheckServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'MemoryChat': grpc.unary_unary_rpc_method_handler(
                    servicer.MemoryChat,
                    request_deserializer=src_dot_memory__check__pb2.Payload.FromString,
                    response_serializer=src_dot_memory__check__pb2.Payload.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'memorycheck.MemoryCheck', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MemoryCheck(object):
    """Interface exported by the server.
    """

    @staticmethod
    def MemoryChat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/memorycheck.MemoryCheck/MemoryChat',
            src_dot_memory__check__pb2.Payload.SerializeToString,
            src_dot_memory__check__pb2.Payload.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
