# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/memory_check.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16src/memory_check.proto\x12\x0bmemorycheck\"\x1a\n\x07Payload\x12\x0f\n\x07message\x18\x01 \x01(\t2I\n\x0bMemoryCheck\x12:\n\nMemoryChat\x12\x14.memorycheck.Payload\x1a\x14.memorycheck.Payload\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'src.memory_check_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PAYLOAD']._serialized_start=39
  _globals['_PAYLOAD']._serialized_end=65
  _globals['_MEMORYCHECK']._serialized_start=67
  _globals['_MEMORYCHECK']._serialized_end=140
# @@protoc_insertion_point(module_scope)
